export const JTHROWS: any = {
  1: {
    id: 1,
    name: 'ippon seoi nage',
    categories: ['nage-waza', 'te-waza'],
    description: 'shoulder throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  2: {
    id: 2,
    name: 'tai-otoshi',
    categories: ['nage-waza', 'te-waza'],
    description: 'body drop',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  3: {
    id: 3,
    name: 'kata-guruma',
    categories: ['nage-waza', 'te-waza'],
    description: 'shoulder wheel',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  4: {
    id: 4,
    name: 'uki-goshi',
    categories: ['nage-waza', 'koshi-waza'],
    description: 'floating hip throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  5: {
    id: 5,
    name: 'o-goshi',
    categories: ['nage-waza', 'koshi-waza'],
    description: 'large hip throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  6: {
    id: 6,
    name: 'koshi-guruma',
    categories: ['nage-waza', 'koshi-waza'],
    description: 'hip wheel',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  7: {
    id: 7,
    name: 'de-ashi-barai',
    categories: ['nage-waza', 'ashi-waza'],
    description: 'forward foot sweep',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  8: {
    id: 8,
    name: 'hiza-guruma',
    categories: ['nage-waza', 'ashi-waza'],
    description: 'knee wheel',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  9: {
    id: 9,
    name: 'sasae-tsurikomi-ashi',
    categories: ['nage-waza', 'ashi-waza'],
    description: 'supporting foot lift-pull throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  10: {
    id: 10,
    name: 'tomoe-nage',
    categories: ['ma-sutemi-waza', 'sutemi-waza'],
    description: 'circular throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  11: {
    id: 11,
    name: 'sumi gaeshi',
    categories: ['ma-sutemi-waza', 'sutemi-waza'],
    description: 'corner throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  12: {
    id: 12,
    name: 'ura-nage',
    categories: ['ma-sutemi-waza', 'sutemi-waza'],
    description: 'back throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
  },
  13: {
    id: 13,
    name: 'yoko-otoshi',
    categories: ['yoko-sutemi-waza', 'sutemi-waza'],
    description: 'side drop',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  14: {
    id: 14,
    name: 'tani-otoshi',
    categories: ['yoko-sutemi-waza', 'sutemi-waza'],
    description: 'valley drop',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  15: {
    id: 15,
    name: 'hane-makikomi',
    categories: ['yoko-sutemi-waza', 'sutemi-waza'],
    description: 'springing wraparound throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  16: {
    id: 16,
    name: 'kusure-kesa-gatame',
    categories: ['katame-waza', 'osae-komi-waza'],
    description: 'modified scarfold hold',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  17: {
    id: 17,
    name: 'kata-gatame',
    categories: ['katame-waza', 'osae-komi-waza'],
    description: 'shoulder hold',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
  },
  18: {
    id: 18,
    name: 'kami-shiho-gatame',
    categories: ['katame-waza', 'osae-komi-waza'],
    description: 'top four-corner hold',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  19: {
    id: 19,
    name: 'nami-juji-jime',
    categories: ['katame-waza', 'shime-waza'],
    description: 'normal cross strangle',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  20: {
    id: 20,
    name: 'gyaku-juji-jime',
    categories: ['katame-waza', 'shime-waza'],
    description: 'reverse cross strangle',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  21: {
    id: 21,
    name: 'kata-juji-jime',
    categories: ['katame-waza', 'shime-waza'],
    description: 'half cross strangle',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  22: {
    id: 22,
    name: 'ude-garami',
    categories: ['katame-waza', 'kansetsu-waza'],
    description: 'entangled arm lock',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  23: {
    id: 23,
    name: 'ude-hishigi-juji-gatame',
    categories: ['katame-waza', 'kansetsu-waza'],
    description: 'cross lock',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  24: {
    id: 24,
    name: 'ude-hishigi-ude-gatame',
    categories: ['katame-waza', 'kansetsu-waza'],
    description: 'arm lock',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
};

//This file structure was copied from the file of the firebase course
//to create a pre-formatted data structure database with Judo Throws
//following the formatting of the training

//1 - Nage-waza (Throwing Techniques): This is the largest group and further divides into subgroups based on mechanics:
//    1 - 1 - X Te-waza (Arm Techniques) - throws using arm manipulations (e.g., Seoi Nage - Shoulder Throw)
//    1 - 2 - X Ashi-waza (Leg Techniques) - throws using leg sweeps or trips (e.g., O soto gari - Major Outer Reap)
//    1 - 3 - X Koshi-waza (Hip Techniques) - throws using hip movements (e.g., Uchi Mata - Inner Thigh Throw)
//2 - Sutemi-waza (Sacrifice Techniques) - throws where you sacrifice your own balance (e.g., Tomoe Nage - Circle Throw)
//3 - katame-waza (Ground Techniques): Techniques for grappling on the ground including pins, chokes, and joint locks.
//--TODO--
//    3 - 1 - X

//4 - Katame-waza (Grappling Techniques): Techniques used to control your opponent standing or on the ground.

// 01: {
// id: 01,
// name: ippon seoi nage,
// categories: ['nage-waza','te-waza'],
// description: 'shoulder throw',
// difficulty:'easy',
// score: 8,
// rank: 'nan-kyu'
// },

//source: https://www.judo-ch.jp/english/dictionary/technique/
