export const JTHROWS: any = {
  1: {
    id: 1,
    name: 'Ippon-seoi-nage',
    categories: ['Te-waza'],
    description: 'Shoulder throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  2: {
    id: 2,
    name: 'Tai-otoshi',
    categories: ['Te-waza'],
    description: 'Body drop',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: 'test-check',
  },
  3: {
    id: 3,
    name: 'Kata-guruma',
    categories: ['Te-waza'],
    description: 'Shoulder wheel',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  4: {
    id: 4,
    name: 'Uki-goshi',
    categories: ['Koshi-waza'],
    description: 'Floating hip throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  5: {
    id: 5,
    name: 'O-goshi',
    categories: ['Koshi-waza'],
    description: 'Large hip throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  6: {
    id: 6,
    name: 'Koshi-guruma',
    categories: ['Koshi-waza'],
    description: 'Hip wheel',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  7: {
    id: 7,
    name: 'De-ashi-barai',
    categories: ['Ashi-waza'],
    description: 'Forward foot sweep',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  8: {
    id: 8,
    name: 'Hiza-guruma',
    categories: ['Ashi-waza'],
    description: 'Knee wheel',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  9: {
    id: 9,
    name: 'Sasae-tsurikomi-ashi',
    categories: ['Ashi-waza'],
    description: 'Supporting foot lift-pull throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  10: {
    id: 10,
    name: 'Tomoe-nage',
    categories: ['Sutemi-waza'],
    description: 'Circular throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  11: {
    id: 11,
    name: 'Sumi-gaeshi',
    categories: ['Sutemi-waza'],
    description: 'Corner throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  12: {
    id: 12,
    name: 'Ura-nage',
    categories: ['Sutemi-waza'],
    description: 'Back throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
  },
  13: {
    id: 13,
    name: 'Yoko-otoshi',
    categories: ['Sutemi-waza'],
    description: 'Side drop',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  14: {
    id: 14,
    name: 'Tani-otoshi',
    categories: ['Sutemi-waza'],
    description: 'Valley drop',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  15: {
    id: 15,
    name: 'Hane-makikomi',
    categories: ['Sutemi-waza'],
    description: 'Springing wraparound throw',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  16: {
    id: 16,
    name: 'Kusure-kesa-gatame',
    categories: ['Osae-komi-waza'],
    description: 'Modified scarfold hold',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  17: {
    id: 17,
    name: 'Kata-gatame',
    categories: ['Osae-komi-waza'],
    description: 'Shoulder hold',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
  },
  18: {
    id: 18,
    name: 'Kami-shiho-gatame',
    categories: ['Osae-komi-waza'],
    description: 'Top four-corner hold',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  19: {
    id: 19,
    name: 'Nami-juji-jime',
    categories: ['Shime-waza'],
    description: 'Normal cross strangle',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  20: {
    id: 20,
    name: 'Gyaku-juji-jime',
    categories: ['Shime-waza'],
    description: 'Reverse cross strangle',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  21: {
    id: 21,
    name: 'Kata-juji-jime',
    categories: ['Shime-waza'],
    description: 'Half cross strangle',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  22: {
    id: 22,
    name: 'Ude-garami',
    categories: ['Kansetsu-waza'],
    description: 'Entangled arm lock',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  23: {
    id: 23,
    name: 'Ude-hishigi-juji-gatame',
    categories: ['Kansetsu-waza'],
    description: 'Cross lock',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
  24: {
    id: 24,
    name: 'Ude-hishigi-ude-gatame',
    categories: ['Kansetsu-waza'],
    description: 'arm lock',
    difficulty: 'easy',
    score: 8,
    rank: 'nan-kyu',
    url: '',
  },
};

//This file structure was copied from the file of the firebase course
//to create a pre-formatted data structure database with Judo Throws
//following the formatting of the training

//1 - Nage-waza (Throwing Techniques): This is the largest group and further divides into subgroups based on mechanics:
//    1 - 1 - X Te-waza (Arm Techniques) - throws using arm manipulations (e.g., Seoi Nage - Shoulder Throw)
//    1 - 2 - X Ashi-waza (Leg Techniques) - throws using leg sweeps or trips (e.g., O soto gari - Major Outer Reap)
//    1 - 3 - X Koshi-waza (Hip Techniques) - throws using hip movements (e.g., Uchi Mata - Inner Thigh Throw)
//2 - Sutemi-waza (Sacrifice Techniques) - throws where you sacrifice your own balance (e.g., Tomoe Nage - Circle Throw)
//3 - katame-waza (Ground Techniques): Techniques for grappling on the ground including pins, chokes, and joint locks.
//--TODO--
//    3 - 1 - X

//4 - Katame-waza (Grappling Techniques): Techniques used to control your opponent standing or on the ground.

// 01: {
// id: 01,
// name: ippon seoi nage,
// categories: ['nage-waza',' Te-waza'],
// description: 'shoulder throw',
// difficulty:'easy',
// score: 8,
// rank: 'nan-kyu'
// },

//source: https://www.judo-ch.jp/english/dictionary/technique/
